<Project>
  <PropertyGroup>
    <Configurations>Debug;Release;Final</Configurations>
    <Platforms>x64</Platforms>

    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <OutputPath>$(MSBuildThisFileDirectory)Bin\$(Platform)\$(Configuration)\$(MSBuildProjectName)\</OutputPath>
    <IntermediateOutputPath>$(MSBuildThisFileDirectory)Intermediate\$(MSBuildProjectName)\$(Platform)\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);GAME_DEBUG</DefineConstants>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);GAME_RELEASE;GAME_DEV</DefineConstants>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Final'">
    <DefineConstants>$(DefineConstants);GAME_FINAL</DefineConstants>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>